title: LUCDA Design
description: We elevate brands
show_downloads: true
# google_analytics: UA-XXXXXX # uncomment and fill in your Google Analytics ID if you have one
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
